apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name:  "aether-app"
  description: sample
  annotations:
    backstage.io/managed-by-location: url:https://github.com/rohit7533/aether-app
    backstage.io/managed-by-origin-location: url:https://github.com/rohit7533/aether-app
    tekton.dev/pipelines: default/aether-app-pipeline # Namespace/PipelineName
    backstage.io/kubernetes-id: "aether-app"
    backstage.io/kubernetes-cluster: 'bsidp-cluster'
    backstage.io/kubernetes-namespace: 'default'
    tektonci/enabled: 'true'
    tektonci/namespace: 'deafult'
    # github.com/project-slug: rohit7533/terraform-aks
    # terraform/workspaces:  #NodeJSAks
    # terraform/organization:  
spec:
  type: service
  owner: "rohit7533"
  lifecycle: production
