apiVersion: apps/v1
kind: Deployment
metadata:
  name: aether-app
  namespace: default
  labels:
    #tekton.dev/pipelines: default/springboot-pipeline
    'backstage.io/kubernetes-id': 'aether-app'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aether-app
  template:
    metadata:
      labels:
        app: aether-app
        'backstage.io/kubernetes-id': 'aether-app'
    spec:
      containers:
        - name: aether-app
          image: backstagdeveacr.azurecr.io/aether-app:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: aether-app
  namespace: default
spec:
  selector:
    app: aether-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer